DROP DATABASE IF EXISTS `bidhub`;

CREATE DATABASE `bidhub`;

USE `bidhub`;

CREATE TABLE `BIDS` (
    `IDBID` INT NOT NULL,
    `BIDAMOUNT` DOUBLE NOT NULL,
    `IDITEM` INT NOT NULL,
    `IDUSER` INT NOT NULL,
    PRIMARY KEY (`IDBID`)
);

CREATE TABLE `CATEGORIES`(
    `IDCATEGORY` INT AUTO_INCREMENT NOT NULL,
    `CATNAME` VARCHAR(255) NOT NULL,
    `CATPARENT` INT,
    PRIMARY KEY(`IDCATEGORY`)
);

CREATE TABLE `IDBIDS`(
    `NAME` VARCHAR(255) NOT NULL,
    `VAL` BIGINT,
    PRIMARY KEY(`NAME`)
);

CREATE TABLE `IDITEMS`(
    `NAME` VARCHAR(255) NOT NULL,
    `VAL` BIGINT,
    PRIMARY KEY(`NAME`)
);

CREATE TABLE `IDQUOTES`(
    `NAME` VARCHAR(255) NOT NULL,
    `VAL` BIGINT,
    PRIMARY KEY(`NAME`)
);

CREATE TABLE `IDUSERS`(
    `NAME` VARCHAR(255) NOT NULL,
    `VAL` BIGINT,
    PRIMARY KEY(`NAME`)
);

CREATE TABLE `ITEMS`(
    `IDITEM` INT NOT NULL,
    `ITEDATEPUBLICATION` TIMESTAMP NOT NULL,
    `ITEDESCRIPTION` VARCHAR(255) NOT NULL,
    `ITEINITIALVALUE` DOUBLE NOT NULL,
    `ITENAME` VARCHAR(255) NOT NULL,
    `ITEONSALE` BOOLEAN NOT NULL,
    `ITEPICKEDUP` BOOLEAN NOT NULL,
    `ITEPICTURE` VARCHAR(1000) NOT NULL,
    `ITESTATE` VARCHAR(255) NOT NULL,
    `IDCATEGORY` INT NOT NULL,
    `IDUSER` INT NOT NULL,
    PRIMARY KEY(`IDITEM`)
);

CREATE TABLE `QUOTES`(
    `ID` INT NOT NULL,
    `AUTHOR` VARCHAR(255),
    `CITATION` VARCHAR(255),
    PRIMARY KEY(`ID`)
);

CREATE TABLE `USERS`(
    `IDUSER` INT NOT NULL,
    `USECREDIT` DOUBLE NOT NULL,
    `USEEMAIL` VARCHAR(255) NOT NULL,
    `USELASTNAME` VARCHAR(255) NOT NULL,
    `USENAME` VARCHAR(255) NOT NULL,
    `USEPASSWORD` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`IDUSER`),
    UNIQUE(`USEEMAIL`)
);

ALTER TABLE `BIDS` ADD FOREIGN KEY (`IDUSER`) REFERENCES `USERS`(`IDUSER`);
ALTER TABLE `CATEGORIES` ADD FOREIGN KEY (`CATPARENT`) REFERENCES `CATEGORIES`(`IDCATEGORY`);
ALTER TABLE `ITEMS` ADD FOREIGN KEY (`IDCATEGORY`) REFERENCES `CATEGORIES`(`IDCATEGORY`);
ALTER TABLE `ITEMS` ADD FOREIGN KEY (`IDUSER`) REFERENCES `USERS`(`IDUSER`);
ALTER TABLE `BIDS` ADD FOREIGN KEY (`IDITEM`) REFERENCES `ITEMS`(`IDITEM`);