openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Bidhub-API
    description: API pour le projet Bidhub
paths:
  /users/{id}:
    get:
      tags:
        - Bidhub-API
      summary: Obtient un utilisateur
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: id de l'utilisateur à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      deprecated: false

components:
  schemas:
    User:
      description: toutes les caractéristiques d'un utilisateur
      type: object
      properties:
        id:
          description: numéro auto-incrémenté de l'utilisateur
          type: integer
          format: int32
        name:
          description: prénom de l'utilisateur
          type: string
        lastName:
          description: nom de l'utilisateur
          type: string
        email:
          description: email de l'utilisateur
          type: string
        credit:
          description: crédit de l'utilisateur
          type: number
          format: double
      title: User
