openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Bidhub-API
    description: API pour le projet Bidhub
paths:
  /users/{id}:
    get:
      tags:
        - Bidhub-API
      summary: Obtient un utilisateur
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: id de l'utilisateur à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      deprecated: false
  /auth/login:
    post:
      tags:
        - Bidhub-API
      summary: Authentifie un utilisateur
      operationId: authenticateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '404':
          description: Not Found
      deprecated: false
  /auth/register:
    post:
      tags:
        - Bidhub-API
      summary: Enregistre un utilisateur
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '201':
          description: Created
        '404':
          description: Not Found
        '409':
          description: Conflict - email already exists

      deprecated: false
  /bids/{id}:
    get:
      tags:
        - Bidhub-API
      summary: Obtient une offre
      operationId: getBid
      parameters:
        - name: id
          in: path
          description: id de l'offre à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Bid'
        '404':
          description: Not Found
      deprecated: false

    delete:
      tags:
        - Bidhub-API
      summary: Supprime une offre
      operationId: deleteBid
      parameters:
        - name: id
          in: path
          description: id de l'offre à supprimer
          required: true
          schema:
            type: integer
            format: int32
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /bids:
    get:
      tags:
        - Bidhub-API
      summary: Obtient toutes les offres
      operationId: getBids
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bid'
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - Bidhub-API
      summary: Crée une offre
      operationId: createBid
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Bid'
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Bid'
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - Bidhub-API
      summary: Modifie une offre
      operationId: updateBid
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Bid'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Bid'
        '404':
          description: Not Found
      deprecated: false

  /items/{id}:
    get:
      tags:
        - Bidhub-API
      summary: Obtient un article
      operationId: getItem
      parameters:
        - name: id
          in: path
          description: id de l'article à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found
      deprecated: false

    delete:
      tags:
        - Bidhub-API
      summary: Supprime un article
      operationId: deleteItem
      parameters:
        - name: id
          in: path
          description: id de l'article à supprimer
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      deprecated: false
  /items:
    get:
      tags:
        - Bidhub-API
      summary: Obtient tous les articles
      operationId: getItems
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - Bidhub-API
      summary: Crée un article
      operationId: createItem
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - Bidhub-API
      summary: Modifie un article
      operationId: updateItem
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found
      deprecated: false

  /categories/{id}:
    get:
      tags:
        - Bidhub-API
      summary: Obtient une catégorie
      operationId: getCategory
      parameters:
        - name: id
          in: path
          description: id de la catégorie à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Not Found
      deprecated: false

    delete:
      tags:
        - Bidhub-API
      summary: Supprime une catégorie
      operationId: deleteCategory
      parameters:
        - name: id
          in: path
          description: id de la catégorie à supprimer
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      deprecated: false

  /categories:
    get:
      tags:
        - Bidhub-API
      summary: Obtient toutes les catégories
      operationId: getCategories
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - Bidhub-API
      summary: Crée une catégorie
      operationId: createCategory
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - Bidhub-API
      summary: Modifie une catégorie
      operationId: updateCategory
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Not Found
      deprecated: false

components:
  schemas:
    User:
      description: toutes les caractéristiques d'un utilisateur
      type: object
      properties:
        idUser:
          description: numéro auto-incrémenté de l'utilisateur
          type: integer
          format: int32
        usePassword:
          description: mot de passe de l'utilisateur
          type: string
        useName:
          description: prénom de l'utilisateur
          type: string
        useLastName:
          description: nom de l'utilisateur
          type: string
        useEmail:
          description: email de l'utilisateur
          type: string
        useCredit:
          description: crédit de l'utilisateur
          type: number
          format: double
      title: User
    Login:
      description: toutes les caractéristiques d'un utilisateur pour l'authentification
      type: object
      properties:
        email:
          description: email de l'utilisateur
          type: string
        password:
          description: mot de passe de l'utilisateur
          type: string
      title: Login
    Token:
      description: token de l'utilisateur
      type: object
      properties:
        token:
          description: token de l'utilisateur
          type: string
      title: Token
    Bid:
      description: toutes les caractéristiques d'une offre
      type: object
      properties:
        idBid:
          description: numéro auto-incrémenté de l'offre
          type: integer
          format: int32
        bidAmount:
          description: montant de l'offre
          type: number
          format: double
        idUser:
          description: numéro de l'utilisateur faisant l'offre
          type: integer
          format: int32
        idItem:
          description: numéro de l'article sur lequel l'offre est faite
          type: integer
          format: int32
      title: Bid
    Item:
      description: toutes les caractéristiques d'un article
      type: object
      properties:
        idItem:
          description: numéro auto-incrémenté de l'article
          type: integer
          format: int32
        iteDescription:
          description: description de l'article
          type: string
        iteInitialValue:
          description: valeur initiale de l'article
          type: number
          format: double
        iteOnSale:
          description: indique si l'article est en vente
          type: boolean
        iteDatePublication:
          description: date de publication de l'article
          type: string
          format: date-time
        idUser:
          description: numéro de l'utilisateur qui a publié l'article
          type: integer
          format: int32
        idCategory:
          description: numéro de la catégorie de l'article
          type: integer
          format: int32
        iteName:
          description: nom de l'article
          type: string
        iteState:
          description: état de l'article
          type: string
        itePicture:
          description: image de l'article
          type: string
        itePickedUp:
          description: indique si l'article a été récupéré
          type: boolean
      title: Item
    RegisterUser:
      description: toutes les caractéristiques d'un utilisateur
      type: object
      properties:
        usePassword:
          description: mot de passe de l'utilisateur
          type: string
        useName:
          description: prénom de l'utilisateur
          type: string
        useLastName:
          description: nom de l'utilisateur
          type: string
        useEmail:
          description: email de l'utilisateur
          type: string
      title: RegisterUser
    LoginUser:
      description: toutes les caractéristiques d'un utilisateur
      type: object
      properties:
        usePassword:
          description: mot de passe de l'utilisateur
          type: string
        useEmail:
          description: email de l'utilisateur
          type: string
      title: LoginUser

    Category:
      description: toutes les caractéristiques d'une catégorie
      type: object
      properties:
        idCategory:
          description: numéro auto-incrémenté de la catégorie
          type: integer
          format: int32
        catName:
          description: nom de la catégorie
          type: string
      title: Category

