openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Bidhub-API
    description: API pour le projet Bidhub
paths:
  /users/{id}:
    get:
      tags:
        - Bidhub-API
      summary: Obtient un utilisateur
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: id de l'utilisateur à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      deprecated: false

  /auth/login:
    post:
      tags:
        - Bidhub-API
      summary: Authentifie un utilisateur
      operationId: authenticateUser
      parameters:
        - name: email
          in: query
          description: email de l'utilisateur
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: mot de passe de l'utilisateur
          required: true
          schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '404':
          description: Not Found
      deprecated: false


components:
  schemas:
    User:
      description: toutes les caractéristiques d'un utilisateur
      type: object
      properties:
        id:
          description: numéro auto-incrémenté de l'utilisateur
          type: integer
          format: int32
        password:
          description: mot de passe de l'utilisateur
          type: string
        name:
          description: prénom de l'utilisateur
          type: string
        lastName:
          description: nom de l'utilisateur
          type: string
        email:
          description: email de l'utilisateur
          type: string
        credit:
          description: crédit de l'utilisateur
          type: number
          format: double
      title: User
    Login:
      description: toutes les caractéristiques d'un utilisateur pour l'authentification
      type: object
      properties:
        email:
          description: email de l'utilisateur
          type: string
        password:
          description: mot de passe de l'utilisateur
          type: string
      title: Login
    Token:
      description: token de l'utilisateur
      type: object
      properties:
        token:
          description: token de l'utilisateur
          type: string
      title: Token
